version: 2.1

orbs:
  node: circleci/node@5.1.0

parameters:
  node_version:
    type: string
    default: '16.15.0'

commands:
  install_deps:
    steps:
      - node/install-packages:
          pkg-manager: yarn
          cache-version: v1-all
          app-dir: ~/repo
          override-ci-command: yarn install --pure-lockfile --ignore-scripts --no-progress

jobs:
  build:
    executor:
      name: node/default
      tag: << pipeline.parameters.node_version >>
    working_directory: ~/repo
    steps:
      - checkout
      - install_deps
      - run: yarn test --maxWorkers=4
      - run: yarn type-check
      - run: yarn lint:ci
